name: mldm-env
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - bioconda
dependencies:
  - python==3.12.0
  - matplotlib==3.10.0
  - pandas==2.2.3
  - scikit-image==0.25.2
  - scikit-learn==1.6.1
  - pydicom==3.0.1
  - shap==0.47.2
  - snakemake==9.3.0
  - snakemake-executor-plugin-slurm==1.2.1
  - graphviz==12.2.1
  - ipykernel==6.29.5
