default-resources:
- slurm_partition="teach_cpu"
- slurm_account="sscm033324"
- mem_mb="1000"
- runtime="6000"
- ntasks="5"
- nodes="5"
jobs: 12
printshellcmds: True
scheduler: greedy
use-conda: True
